name: git-push-service

on:
  push:
    branches: [main]
    paths:
      - git-push-service/**
      - '*.json'
      - e2e-test/**
      - .github/workflows/git-push-service.yaml
  pull_request:
    branches: [main]
    paths:
      - git-push-service/**
      - '*.json'
      - e2e-test/**
      - .github/workflows/git-push-service.yaml

jobs:
  ts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: git-push-service
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn lint
